name: CI

on: [pull_request]

jobs:
  Run_tests_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Run tests
      timeout-minutes: 20
      run: |
        npm i -g appium
        cd tests && npm i
        npm run e2e -- --runType sim12iPhoneX --sauceLab --appPath imagepicker-actions.zip
